(()=>{
'use strict';
const LOGIN={email:'doctor@petfamily.demo',password:'doctor123'};
const STORE='petcare-doctor-workspace-v2';
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{}}catch(e){return {}}};
const saveState=x=>localStorage.setItem(STORE,JSON.stringify(x));
let state=load(),activePet=null;
function injectButton(){
 const welcome=$('#welcome .welcome-actions');
 if(welcome&&!welcome.querySelector('[data-enter-doctor]')){const b=document.createElement('button');b.className='btn btn-secondary btn-xl';b.dataset.enterDoctor='1';b.textContent='DOCTOR LOGIN';welcome.appendChild(b)}
 const top=$('#clinicApp .top-actions');
 if(top&&!top.querySelector('[data-enter-doctor]')){const b=document.createElement('button');b.className='btn btn-secondary';b.dataset.enterDoctor='1';b.textContent='DOCTOR PORTAL';top.prepend(b)}
}
function mount(){
 if($('#doctorLoginScreen'))return;
 document.body.insertAdjacentHTML('beforeend',`
 <section id="doctorLoginScreen" class="doctor-hidden" aria-label="Doctor login"><div class="doctor-shell"><div class="doctor-login-card">
  <div class="doctor-brand"><img src="Pet-Family-Animal-Clinic-and-Grooming-Center.png" alt="Clinic logo"><div><span class="doctor-role-badge">DOCTOR ACCESS ONLY</span><h1>Pet Family Doctor Portal</h1><p>Separate clinical workspace for veterinarians.</p></div></div>
  <label class="doctor-field"><span>Doctor Email</span><input id="doctorEmail" type="email" autocomplete="username" placeholder="doctor@petfamily.demo"></label>
  <label class="doctor-field"><span>Password</span><input id="doctorPassword" type="password" autocomplete="current-password" placeholder="Enter password"></label>
  <div class="doctor-actions"><button class="doctor-btn primary" data-doctor-login>LOGIN AS DOCTOR</button><button class="doctor-btn secondary" data-doctor-fill>ONE-TAP DEMO LOGIN</button><button class="doctor-btn secondary" data-doctor-back>BACK</button></div>
  <div class="doctor-demo-box"><strong>Demo doctor access</strong><br>Email: doctor@petfamily.demo<br>Password: doctor123</div>
 </div></div></section>
 <section id="doctorWorkspace" class="doctor-hidden" aria-label="Doctor workspace">
  <header class="doctor-topbar"><div><strong>🩺 Doctor Workspace</strong><small>Veterinarian · Pet Family Animal Clinic</small></div><div class="doctor-top-actions"><button class="doctor-btn secondary" data-doc-module="dashboard">DASHBOARD</button><button class="doctor-btn secondary" data-doctor-clinic>CLINIC PORTAL</button><button class="doctor-btn danger" data-doctor-logout>LOG OUT</button></div></header>
  <main class="doctor-dashboard">
   <div class="doctor-kpis"><div class="doctor-kpi"><strong id="docPatients">0</strong><small>Patients today</small></div><div class="doctor-kpi"><strong>2</strong><small>Lab results to review</small></div><div class="doctor-kpi"><strong>1</strong><small>Admitted patient</small></div><div class="doctor-kpi"><strong>2</strong><small>Follow-ups due</small></div></div>
   <div class="doctor-layout"><section class="doctor-card"><h2>Today's Patients</h2><div id="doctorPatientList"></div></section><section class="doctor-card"><h3>Doctor Modules</h3><div class="doctor-workflow">
    <button class="doctor-module" data-doc-module="triage"><span>🚨</span>Triage</button><button class="doctor-module" data-doc-module="consult"><span>🩺</span>SOAP Notes</button><button class="doctor-module" data-doc-module="orders"><span>📌</span>Doctor Orders</button><button class="doctor-module" data-doc-module="surgery"><span>🧤</span>Surgery</button><button class="doctor-module" data-doc-module="rounds"><span>🏥</span>Inpatient Rounds</button><button class="doctor-module" data-doc-module="pet"><span>🐾</span>One-Pet</button><button class="doctor-module" data-doc-module="lab"><span>🔬</span>Laboratory</button><button class="doctor-module" data-doc-module="rx"><span>📋</span>Prescriptions</button><button class="doctor-module" data-doc-module="followup"><span>🔔</span>Follow-Up</button><button class="doctor-module" data-doc-module="records"><span>📚</span>Records</button>
   </div><div class="doctor-lock">Doctor-only clinical workspace. Reception, cashier and general staff functions remain separate.</div></section></div>
   <section id="doctorDetail" class="doctor-card doctor-detail"></section>
  </main>
 </section>`);
 renderPatients();renderModule('dashboard');
}
function data(){return window.petcareGetData?.()||{pets:[],appointments:[],vaccinations:[],medications:[]}}
function patients(){return (data().pets||[]).slice(0,5)}
function getPet(id){const d=data();return (d.pets||[]).find(x=>x.id===id)||(d.pets||[])[0]||{id:'demo',name:'Patient',species:'Pet',breed:'—',weight:'—',allergies:'—',conditions:'—',emoji:'🐾'}}
function key(p,s){return `${p.id}:${s}`}
function renderPatients(){const d=data(),pets=patients(),box=$('#doctorPatientList');if(!box)return;$('#docPatients').textContent=pets.length;box.innerHTML=pets.length?pets.map((p,i)=>{const a=(d.appointments||[]).find(x=>x.petId===p.id);return `<div class="doctor-patient"><div><strong>${esc(p.emoji||'🐾')} ${esc(p.name)}</strong><small>${esc(p.breed||p.species||'Pet')} · ${esc(a?.type||'Consultation')} · ${esc(a?.time||['09:00','10:30','14:00'][i%3])}</small></div><button class="doctor-btn secondary" data-open-patient="${esc(p.id)}">OPEN</button></div>`}).join(''):'<p>No patients loaded.</p>'}
function patientHead(p){return `<h2>${esc(p.emoji||'🐾')} ${esc(p.name)} <small class="doctor-pet-meta">${esc(p.species||'Pet')} · ${esc(p.breed||'—')} · ${esc(p.weight||'—')}</small></h2><div class="doctor-alert-strip"><span><strong>Allergy:</strong> ${esc(p.allergies||'None recorded')}</span><span><strong>Condition:</strong> ${esc(p.conditions||'None recorded')}</span></div>`}
function saved(p,m){return state[key(p,m)]||{}}
function renderModule(m,petId){
 const p=getPet(petId||activePet);activePet=p.id;const box=$('#doctorDetail');if(!box)return;const v=saved(p,m),head=patientHead(p);
 const dashboard=`<h2>Doctor Clinical Command Center</h2><p class="doctor-sub">Choose a patient, then move through the clinical workflow.</p><div class="doctor-stage-grid"><button data-doc-module="triage">1. TRIAGE<small>Vitals · urgency · pain</small></button><button data-doc-module="consult">2. SOAP CONSULT<small>Assessment · plan</small></button><button data-doc-module="orders">3. DOCTOR ORDERS<small>Treatment · lab · imaging</small></button><button data-doc-module="surgery">4. SURGERY<small>Pre-op · procedure · recovery</small></button><button data-doc-module="rounds">5. INPATIENT ROUNDS<small>Vitals · meds · nursing updates</small></button></div>`;
 const forms={
 dashboard,
 triage:`${head}<h3>Triage & Vital Signs</h3><div class="doctor-form-grid" data-form="triage"><select name="urgency"><option ${v.urgency==='GREEN'?'selected':''}>GREEN</option><option ${v.urgency==='YELLOW'?'selected':''}>YELLOW</option><option ${v.urgency==='ORANGE'?'selected':''}>ORANGE</option><option ${v.urgency==='RED'?'selected':''}>RED</option></select><input name="reason" value="${esc(v.reason||'')}" placeholder="Reason for visit"><input name="temp" value="${esc(v.temp||'')}" placeholder="Temperature °C"><input name="hr" value="${esc(v.hr||'')}" placeholder="Heart rate bpm"><input name="rr" value="${esc(v.rr||'')}" placeholder="Respiratory rate"><input name="weight" value="${esc(v.weight||p.weight||'')}" placeholder="Weight"><select name="pain"><option>Pain 0</option><option>Pain 1</option><option>Pain 2</option><option>Pain 3</option><option>Pain 4</option><option>Pain 5</option></select><textarea name="notes" placeholder="Triage notes">${esc(v.notes||'')}</textarea><button class="doctor-btn primary" data-save-form="triage">SAVE TRIAGE</button></div>`,
 consult:`${head}<h3>SOAP Consultation</h3><div class="doctor-form-grid" data-form="consult"><textarea name="subjective" placeholder="S — Subjective / owner concerns">${esc(v.subjective||'')}</textarea><textarea name="objective" placeholder="O — Objective findings / examination">${esc(v.objective||'')}</textarea><textarea name="assessment" placeholder="A — Assessment / diagnosis">${esc(v.assessment||'')}</textarea><textarea name="plan" placeholder="P — Plan / treatment / follow-up">${esc(v.plan||'')}</textarea><label class="doctor-check"><input type="checkbox" name="signed" ${v.signed?'checked':''}> Sign and lock doctor note</label><button class="doctor-btn primary" data-save-form="consult">SAVE SOAP NOTE</button></div>`,
 orders:`${head}<h3>Doctor Orders</h3><div class="doctor-form-grid" data-form="orders"><select name="type"><option>Treatment</option><option>Laboratory</option><option>Imaging</option><option>Pharmacy</option><option>Admission</option></select><input name="order" value="${esc(v.order||'')}" placeholder="Order / procedure"><input name="dose" value="${esc(v.dose||'')}" placeholder="Dose / amount"><input name="frequency" value="${esc(v.frequency||'')}" placeholder="Frequency / schedule"><select name="priority"><option>Routine</option><option>Urgent</option><option>STAT</option></select><textarea name="instructions" placeholder="Instructions to treatment room / lab / pharmacy / nursing">${esc(v.instructions||'')}</textarea><button class="doctor-btn primary" data-save-form="orders">SEND DOCTOR ORDER</button></div>`,
 surgery:`${head}<h3>Surgery Workspace</h3><div class="doctor-form-grid" data-form="surgery"><input name="procedure" value="${esc(v.procedure||'')}" placeholder="Procedure"><input name="surgeon" value="${esc(v.surgeon||'')}" placeholder="Surgeon"><textarea name="preop" placeholder="Pre-op assessment / checklist">${esc(v.preop||'')}</textarea><textarea name="anesthesia" placeholder="Anesthesia plan / monitoring">${esc(v.anesthesia||'')}</textarea><textarea name="operative" placeholder="Operative notes">${esc(v.operative||'')}</textarea><textarea name="recovery" placeholder="Recovery / post-op orders">${esc(v.recovery||'')}</textarea><button class="doctor-btn primary" data-save-form="surgery">SAVE SURGERY RECORD</button></div>`,
 rounds:`${head}<h3>Hospitalized Patient Rounds</h3><div class="doctor-form-grid" data-form="rounds"><input name="cage" value="${esc(v.cage||'')}" placeholder="Cage / room"><select name="status"><option>Stable</option><option>Improving</option><option>Monitoring closely</option><option>Critical</option></select><input name="vitals" value="${esc(v.vitals||'')}" placeholder="Latest vitals"><input name="intake" value="${esc(v.intake||'')}" placeholder="Food / water intake"><input name="output" value="${esc(v.output||'')}" placeholder="Urine / stool"><input name="iv" value="${esc(v.iv||'')}" placeholder="IV fluids"><textarea name="meds" placeholder="Medications given / due">${esc(v.meds||'')}</textarea><textarea name="roundnote" placeholder="Doctor round note / nursing instructions">${esc(v.roundnote||'')}</textarea><button class="doctor-btn primary" data-save-form="rounds">SAVE ROUND</button></div>`,
 pet:`${head}<h3>One-Pet Workspace</h3><p>Single-patient view for consultation history, allergies, chronic conditions, vaccinations, medications, labs, procedures, admissions and follow-ups.</p>`,
 lab:`${head}<h3>Laboratory Orders & Results</h3><div class="doctor-form-grid" data-form="lab"><select name="test"><option>CBC</option><option>Blood Chemistry</option><option>Urinalysis</option><option>Fecalysis</option></select><input name="indication" value="${esc(v.indication||'')}" placeholder="Clinical indication"><textarea name="result" placeholder="Result / doctor interpretation">${esc(v.result||'')}</textarea><button class="doctor-btn primary" data-save-form="lab">SAVE LAB REVIEW</button></div>`,
 rx:`${head}<h3>Prescription Approval</h3><div class="doctor-form-grid" data-form="rx"><input name="medicine" value="${esc(v.medicine||'')}" placeholder="Medicine"><input name="dose" value="${esc(v.dose||'')}" placeholder="Dose"><input name="frequency" value="${esc(v.frequency||'')}" placeholder="Frequency"><input name="duration" value="${esc(v.duration||'')}" placeholder="Duration"><textarea name="instructions" placeholder="Special instructions">${esc(v.instructions||'')}</textarea><label class="doctor-check"><input type="checkbox" name="approved" ${v.approved?'checked':''}> Doctor approved for pharmacy release</label><button class="doctor-btn primary" data-save-form="rx">SAVE PRESCRIPTION</button></div>`,
 followup:`${head}<h3>Follow-Up Plan</h3><div class="doctor-form-grid" data-form="followup"><input name="date" type="date" value="${esc(v.date||'')}"><select name="type"><option>Recheck</option><option>Repeat laboratory</option><option>Wound check</option><option>Medication review</option><option>Vaccine booster</option></select><textarea name="instructions" placeholder="Follow-up instructions">${esc(v.instructions||'')}</textarea><button class="doctor-btn primary" data-save-form="followup">SCHEDULE FOLLOW-UP</button></div>`,
 records:`${head}<h3>Medical Record Summary</h3><div class="doctor-record-grid">${['triage','consult','orders','surgery','rounds','lab','rx','followup'].map(x=>`<div><strong>${x.toUpperCase()}</strong><span>${state[key(p,x)]?'Saved record ✓':'No record yet'}</span></div>`).join('')}</div>`
 };
 box.innerHTML=forms[m]||dashboard;
}
function saveForm(type,button){const p=getPet(activePet),form=$(`[data-form="${type}"]`);if(!form)return;const out={};form.querySelectorAll('input,select,textarea').forEach(el=>out[el.name]=el.type==='checkbox'?el.checked:el.value);state[key(p,type)]=out;saveState(state);button.textContent='SAVED ✓';setTimeout(()=>button.textContent=type==='orders'?'SEND DOCTOR ORDER':'SAVE',1100)}
function showLogin(){mount();document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#doctorWorkspace').classList.add('doctor-hidden');$('#doctorLoginScreen').classList.remove('doctor-hidden');scrollTo(0,0)}
function login(){const e=$('#doctorEmail')?.value.trim(),p=$('#doctorPassword')?.value;if(e===LOGIN.email&&p===LOGIN.password){sessionStorage.setItem('petcareDoctorDemo','1');$('#doctorLoginScreen').classList.add('doctor-hidden');$('#doctorWorkspace').classList.remove('doctor-hidden');renderPatients();renderModule('dashboard')}else alert('Doctor login not recognized. Use the one-tap demo login.')}
function leave(){sessionStorage.removeItem('petcareDoctorDemo');$('#doctorWorkspace')?.classList.add('doctor-hidden');$('#doctorLoginScreen')?.classList.add('doctor-hidden');if(typeof window.enter==='function')window.enter('clinic');else location.reload()}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.matches('[data-enter-doctor]'))showLogin();if(t.matches('[data-doctor-fill]')){$('#doctorEmail').value=LOGIN.email;$('#doctorPassword').value=LOGIN.password}if(t.matches('[data-doctor-login]'))login();if(t.matches('[data-doctor-back]')){$('#doctorLoginScreen').classList.add('doctor-hidden');if(typeof window.enter==='function')window.enter('clinic')}if(t.matches('[data-doctor-logout],[data-doctor-clinic]'))leave();if(t.dataset.docModule)renderModule(t.dataset.docModule,activePet);if(t.dataset.openPatient){activePet=t.dataset.openPatient;renderModule('triage',activePet)}if(t.dataset.saveForm)saveForm(t.dataset.saveForm,t)});
function init(){mount();injectButton();if(sessionStorage.getItem('petcareDoctorDemo')==='1'){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#doctorWorkspace').classList.remove('doctor-hidden')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,700);
})();