(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s);
const modules=[['👥','TODAY’S PATIENTS','Queue · triage','dashboard'],['🩺','CONSULTATION','Vitals · SOAP · diagnosis','consult'],['📌','DOCTOR ORDERS','Lab · treatment · admission','orders'],['🔬','LAB & DIAGNOSTICS','Requests · results','lab'],['💉','PREVENTIVE CARE','Vaccines · due dates','preventive'],['🏥','ADMISSION & ROUNDS','Progress · treatment','rounds'],['📋','PRESCRIPTIONS','Dose · duration · sign','rx'],['🏠','FOLLOW-UP & SIGN-OFF','Recheck · audit','followup']];
const state={stage:'WAITING',patient:'Buddy',owner:'Maria Santos'};
const stages=['WAITING','TRIAGE','WITH DOCTOR','ORDERS','LAB / TREATMENT','PHARMACY','CASHIER','COMPLETED'];
function panel(title,body){let p=$('#doctorOrbitPanel');if(!p){p=document.createElement('section');p.id='doctorOrbitPanel';p.className='doctor-card doctor-orbit-panel';$('#doctorOrbitZone')?.after(p)}p.innerHTML='<div class="doc-panel-head"><button data-doc-back>← BACK TO ORBIT</button><h2>'+title+'</h2></div>'+body;p.scrollIntoView({behavior:'smooth',block:'start'})}
const field=(l,n,type='text')=>'<label>'+l+'<input name="'+n+'" type="'+type+'"></label>';
function open(m){
 if(m==='dashboard')return panel("Today's Doctor Dashboard",'<div class="doc-kpi-grid"><div><b>3</b><small>WAITING</small></div><div><b>1</b><small>URGENT</small></div><div><b>2</b><small>FOLLOW-UPS</small></div><div><b>2</b><small>PENDING RESULTS</small></div></div><div class="doc-patient-card"><b>🐶 Buddy</b><span>Maria Santos · General Consultation</span><strong>Current: '+state.stage+'</strong><button data-next-stage>MOVE TO NEXT STAGE</button><button data-doc-module="consult">OPEN CONSULTATION</button></div>');
 if(m==='consult')return panel('Patient Consultation','<div class="doc-alert">ALLERGIES: None recorded · CHRONIC CONDITIONS: None recorded</div><form data-doc-form="consult" class="doc-form">'+field('Temperature','temp')+field('Weight (kg)','weight','number')+field('Chief complaint','complaint')+'<label>SOAP / Examination<textarea name="soap"></textarea></label>'+field('Diagnosis','diagnosis')+'<label>Treatment Plan<textarea name="plan"></textarea></label><button>SAVE CONSULTATION</button></form>');
 if(m==='orders')return panel('Doctor Orders','<form data-doc-form="orders" class="doc-form"><label>Order Type<select name="type"><option>Laboratory</option><option>Imaging</option><option>Treatment</option><option>Admission</option></select></label>'+field('Order / Instructions','order')+'<button>SEND ORDER</button></form>');
 if(m==='lab')return panel('Lab & Diagnostics','<div class="doc-patient-card"><b>CBC — Buddy</b><span>Status: RESULT READY</span><button data-reviewed>MARK REVIEWED</button></div><form data-doc-form="lab" class="doc-form">'+field('New Test Request','test')+'<button>REQUEST TEST</button></form>');
 if(m==='preventive')return panel('Preventive Care','<form data-doc-form="preventive" class="doc-form">'+field('Vaccine / Preventive Treatment','vaccine')+field('Date Given','given','date')+field('Next Due','due','date')+'<button>SAVE & SCHEDULE REMINDER</button></form>');
 if(m==='rounds')return panel('Admission & Rounds','<form data-doc-form="rounds" class="doc-form">'+field('Admission reason','reason')+field('Current vitals','vitals')+'<label>Progress Notes<textarea name="notes"></textarea></label>'+field('Treatment Orders','treatment')+'<button>SAVE ROUND NOTE</button></form>');
 if(m==='rx')return panel('Prescription Builder','<form data-doc-form="rx" class="doc-form">'+field('Medicine','medicine')+field('Dose','dose')+field('Frequency','frequency')+field('Duration','duration')+field('Instructions','instructions')+'<button>SAVE & SIGN PRESCRIPTION</button></form>');
 if(m==='followup')return panel('Follow-Up & Doctor Sign-Off','<form data-doc-form="followup" class="doc-form">'+field('Follow-up Date','date','date')+field('Home Care Instructions','care')+'<label><input type="checkbox" name="sign"> Doctor sign-off: record reviewed and completed</label><button>COMPLETE VISIT & SEND REMINDER</button></form><div class="doc-audit">Audit trail records doctor, date/time and future amendments.</div>');
}
function build(){const dash=$('#doctorWorkspace .doctor-dashboard');if(!dash||$('#doctorOrbitZone'))return;const zone=document.createElement('section');zone.id='doctorOrbitZone';zone.className='doctor-card doctor-orbit-zone';zone.innerHTML='<h2 class="doctor-orbit-title">Doctor Clinical Orbit</h2><div class="doctor-orbit-wrap"><div class="doctor-orbit-ring"></div><button class="doctor-orbit-center" data-doc-module="dashboard"><strong>DOCTOR CLINICAL<br>COMMAND CENTER</strong><small>Tap for today’s flow</small></button>'+modules.map((m,i)=>'<button class="doctor-orbit-node" data-i="'+i+'" data-doc-module="'+m[3]+'"><span>'+m[0]+'</span>'+m[1]+'<small>'+m[2]+'</small></button>').join('')+'</div><div class="doctor-orbit-flow">'+stages.map(x=>'<span>'+x+'</span>').join('<span>→</span>')+'</div>';const first=dash.querySelector('.doctor-kpis');if(first)first.after(zone);else dash.prepend(zone)}
document.addEventListener('click',e=>{const m=e.target.closest('[data-doc-module]');if(m){e.preventDefault();open(m.dataset.docModule);return}if(e.target.closest('[data-doc-back]')){$('#doctorOrbitPanel')?.remove();$('#doctorOrbitZone')?.scrollIntoView({behavior:'smooth'});return}if(e.target.closest('[data-next-stage]')){let i=stages.indexOf(state.stage);state.stage=stages[Math.min(i+1,stages.length-1)];open('dashboard');return}if(e.target.closest('[data-reviewed]')){e.target.textContent='REVIEWED ✓';e.target.disabled=true}},true);
document.addEventListener('submit',e=>{const f=e.target.closest('[data-doc-form]');if(!f)return;e.preventDefault();const key='petcare-doctor-'+f.dataset.docForm;localStorage.setItem(key,JSON.stringify(Object.fromEntries(new FormData(f))));const b=f.querySelector('button');b.textContent='SAVED ✓';setTimeout(()=>b.textContent=f.dataset.docForm==='followup'?'COMPLETE VISIT & SEND REMINDER':'SAVE',1400)},true);
function init(){build()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));else setTimeout(init,500);new MutationObserver(()=>build()).observe(document.body,{childList:true,subtree:true});
})();