(()=>{
'use strict';
const api=window.PetCareSupabase;if(!api)return;
const OLD_KEY='petcare-reminder-orbit-v1';
const toast=msg=>{const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function legacy(){try{return JSON.parse(localStorage.getItem(OLD_KEY)||'null')}catch{return null}}
function install(){if(!api.active||api.state.staff)return;const old=legacy();if(!old?.pets?.length)return;const key='petcare-imported-'+api.state.session.user.id;if(localStorage.getItem(key))return;const panel=document.getElementById('ownerPanel');if(!panel||panel.querySelector('h2')?.textContent?.trim()!=='More'||panel.querySelector('[data-import-demo]'))return;const wrap=panel.querySelector('.secure-extra')||panel.querySelector('.panel-card');const b=document.createElement('button');b.className='btn btn-outline';b.dataset.importDemo='1';b.textContent='IMPORT LOCAL DEMO DATA';b.onclick=()=>run(old,key);wrap?.appendChild(b)}
async function run(old,key){const {count}=await api.state.client.from('pets').select('id',{count:'exact',head:true}).eq('owner_id',api.state.session.user.id);const message=(count||0)>0?'You already have secure pet records. Import will ADD copies of your local demo records and will not overwrite existing secure records. Continue?':'Import your local demo pet-care records into your secure account? Existing secure data will not be overwritten.';if(!confirm(message))return;try{const c=api.state.client,uid=api.state.session.user.id,clinic=api.state.clinic?.id||null,map=new Map();const existing=await c.from('pets').select('microchip_number').eq('owner_id',uid);const chips=new Set((existing.data||[]).map(x=>x.microchip_number).filter(Boolean));for(const p of old.pets){const id=crypto.randomUUID();map.set(p.id,id);const chip=p.microchip&&!chips.has(p.microchip)?p.microchip:null;if(chip)chips.add(chip);const {error}=await c.from('pets').insert({id,owner_id:uid,clinic_id:clinic,name:p.name||'Pet',species:p.species||'Dog',breed:p.breed||null,sex:p.sex||null,birthday:p.birthday||null,weight:p.weight||null,microchip_number:chip,allergies:p.allergies||null,medical_conditions:p.conditions||null,primary_veterinarian:p.vet||null});if(error)throw error}
const rows=(arr,fn)=>(arr||[]).filter(x=>map.has(x.petId)).map(x=>fn(x,map.get(x.petId)));
const jobs=[];
const vacc=rows(old.vaccinations,(x,pid)=>({id:crypto.randomUUID(),pet_id:pid,clinic_id:clinic,vaccine_name:x.name,date_administered:x.given||null,next_due_date:x.due||null,veterinarian:x.vet||null}));if(vacc.length)jobs.push(c.from('vaccinations').insert(vacc));
const rem=rows(old.reminders,(x,pid)=>({id:crypto.randomUUID(),pet_id:pid,clinic_id:clinic,reminder_type:x.type||'Custom',title:x.title,due_date:x.date,status:x.done?'COMPLETED':'UPCOMING',completed_at:x.done?new Date().toISOString():null}));if(rem.length)jobs.push(c.from('reminders').insert(rem));
const meds=rows(old.medications,(x,pid)=>({id:crypto.randomUUID(),pet_id:pid,clinic_id:clinic,medication_name:x.name,dose:x.dose||null,frequency:x.frequency||null,start_date:x.start||null,end_date:x.end||null,prescribing_vet:x.vet||null,status:'ACTIVE'}));if(meds.length)jobs.push(c.from('medications').insert(meds));
const groom=rows(old.grooming,(x,pid)=>({id:crypto.randomUUID(),pet_id:pid,owner_id:uid,clinic_id:clinic,service:x.service,appointment_date:x.next||null,groomer:x.groomer||null,price:x.price||null,status:x.status||'BOOKED'}));if(groom.length)jobs.push(c.from('grooming_records').insert(groom));
const appts=rows(old.appointments,(x,pid)=>({id:crypto.randomUUID(),pet_id:pid,owner_id:uid,clinic_id:clinic,veterinarian:x.vet||null,appointment_type:x.type,appointment_date:x.date,appointment_time:x.time||null,status:x.status||'REQUESTED'}));if(appts.length)jobs.push(c.from('appointments').insert(appts));
const out=await Promise.all(jobs);const err=out.find(r=>r.error)?.error;if(err)throw err;localStorage.setItem(key,new Date().toISOString());alert('Import complete. Pet records, vaccines, reminders, medications, grooming and appointments were added. Demo document metadata was not imported because it does not contain real files.');location.reload()}catch(e){console.error(e);toast(e.message||'Import failed. Secure records were not overwritten.')}}
const o=new MutationObserver(install);window.addEventListener('DOMContentLoaded',()=>{const p=document.getElementById('ownerPanel');if(p)o.observe(p,{childList:true,subtree:true});install()});
})();